import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Main simulation engine for galaxy particles
class GalaxyEngine:
    def __init__(self, count, mass_range=(1, 10), bounds=100):
        self.bounds = bounds
        self.count = count
        self.masses = np.random.uniform(*mass_range, size=(count, 1))
        self.positions = np.random.uniform(-bounds, bounds, size=(count, 3))
        self.speeds = np.zeros((count, 3))
        self.accelerations = np.zeros((count, 3))

    def update(self, dt=0.01, interaction_rate=1.0, black_hole_mass=0.0):
        n = self.count
        acc = np.zeros_like(self.positions)

        for i in range(n):
            force = np.zeros(3)
            for j in range(int(interaction_rate * n)):
                if i == j:
                    continue
                r_vec = self.positions[j] - self.positions[i]
                r_norm2 = np.sum(r_vec**2) + 0.01  # Prevent division by zero
                force += r_vec / r_norm2

            # Add gravitational pull from the center if black hole mass > 0
            if black_hole_mass > 0.0:
                center_vec = -self.positions[i]
                center_r2 = np.sum(center_vec**2) + 0.01
                force += black_hole_mass * center_vec / center_r2

            acc[i] = force / interaction_rate

        self.accelerations = acc
        self.speeds += dt * self.accelerations
        self.positions += dt * self.speeds

        # Keep all particles within the bounded simulation space
        self.positions = np.clip(self.positions, -self.bounds, self.bounds)


# Simple 3D scatter plot to visualize the starfield
def plot_starfield(positions):
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection='3d')
    ax.set_facecolor('black')
    fig.patch.set_facecolor('black')

    ax.scatter(
        positions[:, 0],
        positions[:, 1],
        positions[:, 2],
        c='white',
        s=2,
        alpha=0.8
    )

    ax.set_title('Simulated Starfield', color='white')
    ax.tick_params(colors='white')
    ax.xaxis._axinfo["grid"]['color'] = "white"
    ax.yaxis._axinfo["grid"]['color'] = "white"
    ax.zaxis._axinfo["grid"]['color'] = "white"

    plt.show()


# Represents a directional input force generated by a slingshot gesture
class Slingshot:
    def __init__(self, norm=np.array([0.0, 0.0]), length=0.0):
        self.norm = norm
        self.length = length

    @staticmethod
    def from_positions(start_pos, end_pos):
        """
        Simulates a slingshot generated by dragging the mouse:
        start_pos = drag start point, end_pos = release point
        """
        dist = start_pos - end_pos
        length = np.linalg.norm(dist)
        if length == 0:
            return Slingshot()
        norm = dist / length
        return Slingshot(norm, length)
    
class Morton:
    @staticmethod
    def scale_to_grid(pos, min_val, max_val):
        """Clamp and normalize position to a 0–2047 grid."""
        if max_val <= min_val:
            return 0
        clamped = np.clip(pos, min_val, max_val)
        normalized = (clamped - min_val) / (max_val - min_val)
        return int(normalized * 2047)

    @staticmethod
    def spread_bits(x):
        """Spread 11-bit integer bits to prepare for Morton encoding."""
        x &= 0x7FF
        x = (x | (x << 8)) & 0x00FF00FF00FF00FF
        x = (x | (x << 4)) & 0x0F0F0F0F0F0F0F0F
        x = (x | (x << 2)) & 0x3333333333333333
        x = (x | (x << 1)) & 0x5555555555555555
        return x

    @staticmethod
    def morton2D(x, y):
        """Combine two spread integers into a 2D Morton code."""
        return Morton.spread_bits(x) | (Morton.spread_bits(y) << 1)

    @staticmethod
    def compute_morton_keys(p_particles, min_position, size):
        """
        Assign Morton keys to particle physics objects based on position.
        p_particles: list of ParticlePhysics-like objects with `.pos` and `.mortonKey`
        min_position: np.array([x, y])
        """
        max_x = min_position[0] + max(size, 1e-6)
        max_y = min_position[1] + max(size, 1e-6)

        for p in p_particles:
            ix = Morton.scale_to_grid(p.pos[0], min_position[0], max_x)
            iy = Morton.scale_to_grid(p.pos[1], min_position[1], max_y)
            p.mortonKey = Morton.morton2D(ix, iy)

    @staticmethod
    def sort_particles_by_morton_key(p_particles, r_particles):
        """
        Sort both physics and rendering particles by mortonKey in-place.
        """
        indices = list(range(len(p_particles)))
        indices.sort(key=lambda i: p_particles[i].mortonKey)

        p_sorted = [p_particles[i] for i in indices]
        r_sorted = [r_particles[i] for i in indices]

        # Update in-place
        p_particles[:] = p_sorted
        r_particles[:] = r_sorted